#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2020.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Oct 21 10:27:36 HST 2021
# SW Build 3064766 on Wed Nov 18 09:12:47 MST 2020
#
# Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb1_behav -key {Behavioral:sim_1:Functional:tb1} -tclbatch tb1.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home2/shivang/github/vivado_ex/build/project_1/tb1_behav.wcfg -log simulate.log"
xsim tb1_behav -key {Behavioral:sim_1:Functional:tb1} -tclbatch tb1.tcl -protoinst "protoinst_files/design_1.protoinst" -view /home2/shivang/github/vivado_ex/build/project_1/tb1_behav.wcfg -log simulate.log

